# Generated by Django 3.2.14 on 2022-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_to_be_done', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('city', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
