# Generated by Django 3.2.14 on 2022-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_plumberprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumberprofile',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
