# Generated by Django 3.2.14 on 2022-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_plumberprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumberprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plumberprofile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
