# Generated by Django 3.2.14 on 2022-09-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plumberprofile',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
            preserve_default=False,
        ),
    ]
