# Generated by Django 3.2.14 on 2022-09-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plumberprofile',
            name='role',
        ),
    ]
